modules:
  default:
    lmod:
      core_compilers:
        - gcc@7.3.1
      all:
        autoload: direct
      hierarchy:
        - mpi
    roots:
      tcl: /apps/software/spack/modules/tcl
      lmod: /apps/software/spack/modules/lmod
    enable:
      - lmod

    tcl:
      all:
        autoload: none

  prefix_inspections:
    ./bin:
      - PATH
    ./man:
      - MANPATH
    ./share/man:
      - MANPATH
    ./share/aclocal:
      - ACLOCAL_PATH
    ./lib/pkgconfig:
      - PKG_CONFIG_PATH
    ./lib64/pkgconfig:
      - PKG_CONFIG_PATH
    ./share/pkgconfig:
      - PKG_CONFIG_PATH
    ./:
      - CMAKE_PREFIX_PATH

  # These are configurations for the module set named "default"
