---

- name: Ubuntu - Install Gromacs
  hosts: localhost
  tasks:
    - name: Install gromacs with sbatch
      become: yes
      become_user: ubuntu
      ansible.builtin.shell: |
        chmod 777 install-gromacs.sh
        echo "Submitting gromacs job to slurm"
        sbatch ./install-gromacs.sh
