---
- name: Install Gromacs
  hosts: localhost
  tasks:
    - name: Copy spack packages file
      ansible.builtin.copy:
        src: ./install-gromacs.sh
        dest: /home/ec2-user/install-gromacs.sh
        owner: ec2-user
        group: ec2-user
        mode: '0777'
    # TODO this needs to be done per node
    - name: Create spack source script
      ansible.builtin.shell: |
        echo "export SPACK_ROOT=/apps/spack" > spack.sh
        echo "source /apps/spack/share/spack/setup-env.sh" >> spack.sh
        export SPACK_ROOT=/apps/spack
        source /apps/spack/share/spack/setup-env.sh
        sudo chown -R ec2-user:ec2-user /apps/spack/
        
        # Install the rolling binary cache
        # https://aws.amazon.com/blogs/hpc/introducing-the-spack-rolling-binary-cache/
        spack mirror add binary_mirror https://binaries.spack.io/develop
        spack buildcache keys --install --trust
        
        cd /home/ec2-user
        chmod 777 install-gromacs.sh
        sbatch ./install-gromacs.sh
