# Prepare directories as root
---
- name: Include system users
  ansible.builtin.import_playbook: ../system_user.yaml
- name: Prepare directories
  hosts: localhost
  vars:
    directories:
      - { path: "/apps/software-configs", type: "directory" }
      - { path: "/apps/easybuild/4.5.4/modules/all", type: "directory" }
      - { path: "/apps/easybuild/4.5.4", type: "directory" }
      - { path: "/apps/software-configs/jupyterhub", type: "directory" }
      - { path: "/scratch/reference", type: "directory" }
  tasks:
    - name: Alinux2 - Software and EasyBuild dirs
      become: yes
      ansible.builtin.file:
        path: "{{item.path}}"
        state: "{{item.type}}"
        mode: '0755'
        owner: "ec2-user"
        group: "ec2-user"
      loop: "{{directories}}"
      when: ansible_os_family == "RedHat"
    - name: Ubuntu - Software and EasyBuild dirs
      become: yes
      ansible.builtin.file:
        path: "{{item.path}}"
        state: "{{item.type}}"
        mode: '0755'
        owner: "ubuntu"
        group: "ubuntu"
      loop: "{{directories}}"
      when: ansible_os_family == "Debian"
