---
- name: Include system users
  ansible.builtin.import_playbook: ../system_user.yaml
- name: Install Spack
  hosts: localhost
  tasks:
    - name: Create spack packages directory
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.file:
        dest: /home/"{{system_user}}"/.spack
        state: directory
        mode: '0755'
        owner: "{{system_user}}"
        group: "{{system_user}}"
    - name: Create spack apps directory
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.file:
        path: /apps/spack
        state: directory
        mode: '0755'
        owner: "{{system_user}}"
        group: "{{system_user}}"
    - name: Create spack local mirror
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.file:
        path: /apps/software/spack/mirror
        state: directory
        mode: '0755'
        owner: "{{system_user}}"
        group: "{{system_user}}"
    - name: Create spack apps directory 0.19
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.file:
        path: /apps/software-configs/spack/0.19.0
        state: directory
        mode: '0755'
        owner: "{{system_user}}"
        group: "{{system_user}}"
    - name: Create spack apps directory 0.20
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.file:
        path: /apps/software-configs/spack/0.20.0
        state: directory
        mode: '0755'
        owner: "{{system_user}}"
        group: "{{system_user}}"
    - name: Git checkout - Latest
      become: yes
      become_user: "{{system_user}}"
      ignore_errors: yes
      ansible.builtin.git:
        repo: https://github.com/spack/spack.git
        dest: /apps/software-configs/spack/latest
        version: develop
        force: yes
    - name: Git checkout - 0.19.0
      become: yes
      become_user: "{{system_user}}"
      ignore_errors: yes
      ansible.builtin.git:
        repo: https://github.com/spack/spack.git
        dest: /apps/software-configs/spack/0.19.0
        version: v0.19.0
        force: yes
    - name: Git checkout - 0.20.0
      become: yes
      become_user: "{{system_user}}"
      ignore_errors: yes
      ansible.builtin.git:
        repo: https://github.com/spack/spack.git
        dest: /apps/software-configs/spack/0.20.0
        version: develop
        force: yes
    - name: BioAnalyze Spack
      become: yes
      become_user: "{{system_user}}"
      ignore_errors: yes
      ansible.builtin.git:
        repo: https://github.com/dabble-of-devops-bioanalyze/bioanalyze-spack
        dest: /apps/software-configs/bioanalyze-spack
        force: yes
    - name: Create spack source script - 0.19.0
      become: yes
      become_user: "{{system_user}}"
      ignore_errors: yes
      ansible.builtin.shell: |
        export SPACK_ROOT=/apps/software-configs/spack/latest
        source ${SPACK_ROOT}/share/spack/setup-env.sh 
        
        # Install the rolling binary cache
        # https://aws.amazon.com/blogs/hpc/introducing-the-spack-rolling-binary-cache/
        spack mirror add binary_mirror https://binaries.spack.io/develop
        spack buildcache keys --install --trust
        
        cd /apps/software-configs/bioanalyze-spack
        spack repo add .
    - name: Copy spack config file
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.copy:
        src: ./files/spack/config.yaml
        dest: /apps/software-configs/spack/latest/etc/spack/config.yaml
        owner: "{{system_user}}"
        group: "{{system_user}}"
        mode: '0644'
    - name: Copy spack mirrors file
      become: yes
      #      # become_user: "{{system_user}}"
      ansible.builtin.copy:
        src: ./files/spack/mirrors.yaml
        dest: /apps/software-configs/spack/latest/etc/spack/mirrors.yaml
        owner: "{{system_user}}"
        group: "{{system_user}}"
        mode: '0644'
    - name: Copy spack packages file
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.copy:
        src: ./files/spack/spack-packages.yaml
        dest: /apps/software-configs/spack/latest/etc/spack/packages.yaml
        owner: "{{system_user}}"
        group: "{{system_user}}"
        mode: '0644'
    - name: Copy spack modules file
      become: yes
      # become_user: "{{system_user}}"
      ansible.builtin.copy:
        src: ./files/spack/modules.yaml
        dest: /apps/software-configs/spack/latest/etc/spack/modules.yaml
        owner: "{{system_user}}"
        group: "{{system_user}}"
        mode: '0644'
