---
- name: Install Spack
  hosts: localhost
  vars:
    spack_root: /apps/software-configs/spack/v0.19.1
    spack_post_init: |
      export SPACK_ROOT=/apps/software-configs/spack/v0.19.1
      source ${SPACK_ROOT}/share/spack/setup-env.sh 
      
      # Install the rolling binary cache
      # https://aws.amazon.com/blogs/hpc/introducing-the-spack-rolling-binary-cache/
      spack mirror add binary_mirror https://binaries.spack.io/develop
      spack buildcache keys --install --trust
      
      spack mirror add E4S https://cache.e4s.io
      spack buildcache keys -it
      
      cd /apps/software-configs/bioanalyze-spack
      spack repo add .

    git_repos:
      - {
        repo: "https://github.com/spack/spack.git",
        dest: "/apps/software-configs/spack/v0.19.1",
        version: "v0.19.1",
      }
      - {
        repo: "https://github.com/spack/spack.git",
        dest: "/apps/software-configs/spack/latest",
        version: "develop",
      }
      #      - {
      #        repo: "https://github.com/spack/spack.git",
      #        dest: "/apps/software-configs/spack/0.19.0",
      #        version: "v.0.19.0",
      #      }
      - {
        repo: "https://github.com/dabble-of-devops-bioanalyze/bioanalyze-spack",
        dest: "/apps/software-configs/bioanalyze-spack",
        version: "main",
      }
    spack_configs:
      - {
        src: "./files/spack/config.yaml",
        dest: "/apps/software-configs/spack/v0.19.1/etc/spack/config.yaml",
        mode: '0644'
      }
      - {
        src: "./files/spack/mirrors.yaml",
        dest: "/apps/software-configs/spack/v0.19.1/etc/spack/mirrors.yaml",
        mode: '0644'
      }
      - {
        src: "./files/spack/spack-packages.yaml",
        dest: "/apps/software-configs/spack/v0.19.1/etc/spack/packages.yaml",
        mode: '0644'
      }
      - {
        src: "./files/spack/modules.yaml",
        dest: "/apps/software-configs/spack/v0.19.1/etc/spack/modules.yaml",
        mode: '0644'
      }
  tasks:
    - name: Alinux2 - Git checkout spack
      when: ansible_os_family == "RedHat"
      become: yes
      become_user: "ec2-user"
      ignore_errors: yes
      ansible.builtin.git:
        repo: "{{item.repo}}"
        dest: "{{item.dest}}"
        version: "{{item.version}}"
        force: yes
      loop: "{{git_repos}}"
    - name: Ubuntu - Git checkout spack
      when: ansible_os_family == "Debian"
      become: yes
      become_user: "ubuntu"
      ignore_errors: yes
      ansible.builtin.git:
        repo: "{{item.repo}}"
        dest: "{{item.dest}}"
        version: "{{item.version}}"
        force: yes
      loop: "{{git_repos}}"
    - name: Alinux2 - Spack config files
      when: ansible_os_family == "RedHat"
      become: yes
      become_user: "ec2-user"
      ansible.builtin.copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        mode: "{{item.mode}}"
        owner: "ec2-user"
        group: "ec2-user"
      loop: "{{spack_configs}}"
    - name: Ubuntu - Spack config files
      when: ansible_os_family == "Debian"
      become: yes
      become_user: "ubuntu"
      ansible.builtin.copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        mode: "{{item.mode}}"
        owner: "ubuntu"
        group: "ubuntu"
      loop: "{{spack_configs}}"
