---
- name: Install Spack
  hosts: localhost
  tasks:
    - name: Create spack packages directory
      become: yes
      become_user: ec2-user
      ansible.builtin.file:
        dest: /home/ec2-user/.spack
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user
    - name: Copy spack packages file
      become: yes
      become_user: ec2-user
      ansible.builtin.copy:
        src: ./files/spack/spack-packages.yaml
        dest: /home/ec2-user/.spack/packages.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'
    - name: Create spack apps directory
      become: yes
      become_user: ec2-user
      ansible.builtin.file:
        path: /apps/spack
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user
    - name: Create spack local mirror
      become: yes
      become_user: ec2-user
      ansible.builtin.file:
        path: /apps/spack/mirror
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user
    - name: Create spack apps directory 0.19
      become: yes
      become_user: ec2-user
      ansible.builtin.file:
        path: /apps/spack/0.19.0
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user
    - name: Git checkout - 0.19.0
      become: yes
      become_user: ec2-user
      ansible.builtin.git:
        repo: https://github.com/spack/spack.git
        dest: /apps/spack/0.19.0
        version: v0.19.0
        force: yes

    - name: Create spack source script - 0.19.0
      become: yes
      become_user: ec2-user
      ansible.builtin.shell: |
        export SPACK_ROOT=/apps/spack/0.19.0
        source /apps/spack/0.19.0/share/spack/setup-env.sh 
        
        # Install the rolling binary cache
        # https://aws.amazon.com/blogs/hpc/introducing-the-spack-rolling-binary-cache/
        spack mirror add binary_mirror https://binaries.spack.io/develop
        spack buildcache keys --install --trust
