---
- name: Install Spack
  hosts: localhost
  tasks:
    - name: Create spack packages directory
      become: yes
      ansible.builtin.file:
        dest: /home/ec2-user/.spack
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user
    - name: Copy spack packages file
      become: yes
      ansible.builtin.copy:
        src: ./files/spack/spack-packages.yaml
        dest: /home/ec2-user/.spack/packages.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'
    - name: Create spack apps directory
      become: yes
      ansible.builtin.file:
        path: /apps/spack
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user
    - name: Git checkout - develop
      ansible.builtin.git:
        repo: https://github.com/spack/spack.git
        dest: /apps/spack/0.19.0
        version: develop
        force: yes
    - name: Git checkout - 0.18.1
      ansible.builtin.git:
        repo: https://github.com/spack/spack.git
        dest: /apps/spack/0.18.1
        version: v0.18.1
        force: yes
    - name: Create spack source script - 0.18.1
      ansible.builtin.shell: |
        export SPACK_ROOT=/apps/spack/0.18.1
        source /apps/spack/share/spack/0.18.1/setup-env.sh
        
        # Install the rolling binary cache
        # https://aws.amazon.com/blogs/hpc/introducing-the-spack-rolling-binary-cache/
        spack mirror add binary_mirror https://binaries.spack.io/develop
        spack buildcache keys --install --trust

    - name: Create spack source script - 0.19.0
      ansible.builtin.shell: |
        export SPACK_ROOT=/apps/spack/0.19.0
        source /apps/spack/share/spack/0.19.0/setup-env.sh
        
        # Install the rolling binary cache
        # https://aws.amazon.com/blogs/hpc/introducing-the-spack-rolling-binary-cache/
        spack mirror add binary_mirror https://binaries.spack.io/develop
        spack buildcache keys --install --trust
