---
- name: Force rerun bootstrap scripts
  hosts: localhost
  vars:
    # the system user is either ubuntu or alinux2
    system_user: "ubuntu"
  tasks:
    - name: Rerun bootstrap scripts
      become: yes
      ansible.builtin.shell: |
        source /usr/share/lmod/lmod/init/bash
        cd /home/{{system_user}}/bootstrap-scripts
        # bootstrap-scripts/install_all_the_things.sh 
        sudo ./install_all_the_things.sh
