#######################################################
# Yum packages
# These should all be installed on the base ami
# This is a failsafe to ensure all packages are installed
######################################################

---
- name: Install yum packages
  hosts: localhost
  tasks:

    - name: Install the 'Development tools' package group
      ignore_errors: yes
      ansible.builtin.yum:
        name: "@Development tools"
        state: present
        enablerepo: "epel"

    - name: Install Gnome Desktop
      ignore_errors: yes
      become: yes
      ansible.builtin.shell: |
        sudo amazon-linux-extras install -y epel
        sudo amazon-linux-extras install -y R4
        sudo yum-config-manager --enable epel
        sudo yum -y groups install "GNOME Desktop"

    - name: Install the 'Gnome desktop' environment group
      ignore_errors: yes
      ansible.builtin.yum:
        name: "@^gnome-desktop-environment"
        state: present
        enablerepo: "epel"

    - name: Install openssl packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - openssl
          - openssl-devel
        state: present
        enablerepo: "epel"

    - name: Install system packages for R4
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - zlib-devel
          - libxml2-devel
          - xorg-x11-server-Xorg
        state: present
        enablerepo: "epel"

    - name: Install system packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - curl
          - unzip
          - wget
          - git
          - gitflow
          - zsh
          - sudo
        state: present
        enablerepo: "epel"

    - name: Install ftp packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - vsftpd
        state: present
        enablerepo: "epel"

    - name: Install go packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - golang
        state: present
        enablerepo: "epel"

    - name: Install perl packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - perl-devel
          - perl-threads
        state: present
        enablerepo: "epel"

    - name: Install python packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - python3
          - python3-devel
        state: present
        enablerepo: "epel"

    - name: Install file system packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - amazon-efs-utils
          - quota
          - s3fs-fuse
          - aria2
          - tree
        state: present
        enablerepo: "epel"

    - name: Install system monitoring packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - htop
          - atop
        state: present
        enablerepo: "epel"

    - name: Install singularity packages
      ignore_errors: yes
      ansible.builtin.yum:
        name:
          - libuuid-devel
          - libseccomp-devel
          - squashfs-tools
          - singularity-runtime
          - singularity
        state: present
        enablerepo: "epel"

    - name: Install R4
      ignore_errors: yes
      become: yes
      ansible.builtin.shell: |
        sudo amazon-linux-extras install -y epel
        sudo amazon-linux-extras install -y R4
