#######################################################
# Yum packages
# These should all be installed on the base ami
# This is a failsafe to ensure all packages are installed
######################################################

---
- name: Install yum packages
  hosts: localhost
  tasks:

    - name: Install the 'Development tools' package group
      ansible.builtin.yum:
        name: "@Development tools"
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install the 'Gnome desktop' environment group
      ansible.builtin.yum:
        name: "@^gnome-desktop-environment"
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install openssl packages
      ansible.builtin.yum:
        name:
          - openssl
          - openssl-devel
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install system packages
      ansible.builtin.yum:
        name:
          - curl
          - unzip
          - wget
          - git
          - gitflow
          - zsh
          - sudo
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install ftp packages
      ansible.builtin.yum:
        name:
          - vsftpd
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install go packages
      ansible.builtin.yum:
        name:
          - golang
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install perl packages
      ansible.builtin.yum:
        name:
          - perl-devel
          - perl-threads
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install python packages
      ansible.builtin.yum:
        name:
          - python3
          - python3-devel
          - pip3
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install file system packages
      ansible.builtin.yum:
        name:
          - amazon-efs-utils
          - quota
          - s3fs-fuse
          - tree
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install system monitoring packages
      ansible.builtin.yum:
        name:
          - htop
          - atop
        ignore_errors: yes
        state: present
        enablerepo: "epel"

    - name: Install singularity packages
      ansible.builtin.yum:
        name:
          - libuuid-devel
          - libseccomp-devel
          - squashfs-tools
          - singularity-runtime
          - singularity
        ignore_errors: yes
        state: present
        enablerepo: "epel"
